project_id = "bvplrcqhscqcsyxuxbcr"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://8ae45b9b-9c44-4296-8984-541ba17f8358.lovableproject.com"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.process-bulk-upload]
verify_jwt = true

[functions.geocode-location]
verify_jwt = false

[functions.location-autocomplete]
verify_jwt = false

[functions.batch-geocode-providers]
verify_jwt = false

[functions.enrich-school-data]
verify_jwt = true

[functions.import-schools-with-locations]
verify_jwt = false

[functions.migrate-company-locations]
verify_jwt = false

[functions.api-data-access]
verify_jwt = false

[functions.api-key-management]
verify_jwt = true

[functions.credit-management]
verify_jwt = true

[functions.unlock-contact-info]
verify_jwt = true

[functions.export-providers]
verify_jwt = true