-- Insert sample data for all tables

-- Sample Physical Therapists
INSERT INTO public.providers (name, license_number, license_state, specializations, years_experience, phone, email, website, city, state, bio) VALUES
('Dr. Sarah Johnson', 'PT12345', 'CA', ARRAY['Orthopedic', 'Sports Medicine'], 8, '(555) 123-4567', 'sarah.johnson@email.com', 'www.sarahpttherapy.com', 'Los Angeles', 'CA', 'Specializing in sports injury rehabilitation and orthopedic recovery. Over 8 years helping athletes return to peak performance.'),
('Michael Chen, DPT', 'PT67890', 'NY', ARRAY['Neurological', 'Pediatric'], 12, '(555) 987-6543', 'mchen@neuropt.com', NULL, 'New York', 'NY', 'Expert in neurological rehabilitation with focus on stroke recovery and pediatric developmental disorders.'),
('Dr. Emily Rodriguez', 'PT11111', 'TX', ARRAY['Geriatric', 'Balance Training'], 15, '(555) 456-7890', 'emily@seniorcare.com', 'www.geriatricpt.com', 'Austin', 'TX', 'Dedicated to improving quality of life for seniors through specialized geriatric physical therapy and fall prevention.'),
('James Wilson', 'PT22222', 'FL', ARRAY['Aquatic Therapy', 'Post-Surgical'], 6, '(555) 321-0987', 'jwilson@aquapt.com', NULL, 'Miami', 'FL', 'Certified in aquatic therapy techniques for post-surgical recovery and chronic pain management.'),
('Dr. Lisa Park', 'PT33333', 'WA', ARRAY['Women''s Health', 'Pelvic Floor'], 10, '(555) 654-3210', 'lpark@womenshealth.com', 'www.womenspt.com', 'Seattle', 'WA', 'Specialized care for women''s health issues including prenatal, postpartum, and pelvic floor dysfunction.');

-- Sample Companies
INSERT INTO public.companies (name, company_type, description, employee_count, founded_year, website, company_locations, services) VALUES
('HealthFirst Rehabilitation', 'Clinic Chain', 'Leading provider of outpatient physical therapy services with locations across the West Coast.', 250, 2010, 'www.healthfirstrehab.com', ARRAY['California', 'Oregon', 'Washington'], ARRAY['Outpatient PT', 'Sports Medicine', 'Occupational Therapy']),
('Advanced Sports Medicine Institute', 'Specialty Clinic', 'Elite sports medicine facility serving professional athletes and weekend warriors alike.', 45, 2015, 'www.advancedsports.com', ARRAY['Colorado'], ARRAY['Sports Medicine', 'Performance Training', 'Injury Prevention']),
('MedEquip Solutions', 'Equipment Supplier', 'Comprehensive supplier of physical therapy equipment and rehabilitation technology.', 120, 2008, 'www.medequipsolutions.com', ARRAY['Illinois', 'Indiana', 'Wisconsin'], ARRAY['Equipment Sales', 'Installation', 'Training', 'Maintenance']),
('TeleRehab Connect', 'Technology', 'Revolutionary telehealth platform connecting patients with licensed physical therapists remotely.', 85, 2020, 'www.telerehabconnect.com', ARRAY['Remote'], ARRAY['Telehealth Platform', 'Remote Monitoring', 'Digital Assessments']),
('PT Staffing Pro', 'Staffing Agency', 'Premier staffing agency specializing in placing qualified physical therapists nationwide.', 30, 2012, 'www.ptstaffingpro.com', ARRAY['Nationwide'], ARRAY['Permanent Placement', 'Travel Assignments', 'Per Diem Staffing']);

-- Sample Schools
INSERT INTO public.schools (name, city, state, description, accreditation, program_length_months, tuition_per_year, average_class_size, programs_offered, faculty_count, specializations) VALUES
('University of Southern California', 'Los Angeles', 'CA', 'Top-ranked DPT program known for innovation in movement science and clinical excellence.', 'CAPTE Accredited', 36, 45000.00, 85, ARRAY['Doctor of Physical Therapy (DPT)', 'PhD in Physical Therapy'], 25, ARRAY['Neurological', 'Orthopedic', 'Cardiovascular']),
('Northwestern University', 'Chicago', 'IL', 'Premier physical therapy education with strong emphasis on evidence-based practice.', 'CAPTE Accredited', 30, 52000.00, 72, ARRAY['Doctor of Physical Therapy (DPT)'], 18, ARRAY['Sports Medicine', 'Women''s Health', 'Pediatric']),
('Duke University', 'Durham', 'NC', 'Highly selective program combining rigorous academics with extensive clinical training.', 'CAPTE Accredited', 33, 48000.00, 68, ARRAY['Doctor of Physical Therapy (DPT)', 'Transitional DPT'], 22, ARRAY['Orthopedic', 'Neurological', 'Research Methods']),
('University of Washington', 'Seattle', 'WA', 'Public university offering excellent PT education with focus on underserved populations.', 'CAPTE Accredited', 32, 28000.00, 90, ARRAY['Doctor of Physical Therapy (DPT)'], 20, ARRAY['Community Health', 'Geriatric', 'Technology Integration']),
('Emory University', 'Atlanta', 'GA', 'Innovative curriculum emphasizing interprofessional education and global health perspectives.', 'CAPTE Accredited', 34, 46000.00, 75, ARRAY['Doctor of Physical Therapy (DPT)'], 16, ARRAY['Global Health', 'Research', 'Interprofessional Care']);

-- Sample Job Listings (referencing the companies we just created)
INSERT INTO public.job_listings (title, company_id, city, state, description, requirements, salary_min, salary_max, employment_type, experience_level, is_remote) VALUES
('Physical Therapist - Outpatient Orthopedics', (SELECT id FROM public.companies WHERE name = 'HealthFirst Rehabilitation' LIMIT 1), 'San Diego', 'CA', 'Join our dynamic team treating orthopedic conditions in a state-of-the-art outpatient facility. Excellent mentorship and growth opportunities.', 'DPT degree, CA state license, 1+ years experience preferred', 75000, 95000, 'Full-time', 'Entry to Mid-level', false),
('Senior Sports Physical Therapist', (SELECT id FROM public.companies WHERE name = 'Advanced Sports Medicine Institute' LIMIT 1), 'Denver', 'CO', 'Lead position working with elite athletes. Opportunity to travel with professional sports teams and develop cutting-edge treatment protocols.', 'DPT degree, Sports Certification, 5+ years sports medicine experience', 90000, 120000, 'Full-time', 'Senior', false),
('Clinical Education Specialist', (SELECT id FROM public.companies WHERE name = 'MedEquip Solutions' LIMIT 1), 'Chicago', 'IL', 'Train healthcare professionals on new rehabilitation equipment. Combination of clinical expertise and education. Travel required.', 'DPT degree, 3+ years clinical experience, teaching experience preferred', 80000, 100000, 'Full-time', 'Mid-level', false),
('Telehealth Physical Therapist', (SELECT id FROM public.companies WHERE name = 'TeleRehab Connect' LIMIT 1), 'Remote', 'Remote', 'Provide virtual physical therapy consultations and treatment planning. Flexible schedule, work from anywhere.', 'DPT degree, active state license, telehealth experience preferred', 70000, 90000, 'Full-time', 'All Levels', true),
('Travel Physical Therapist - Contract', (SELECT id FROM public.companies WHERE name = 'PT Staffing Pro' LIMIT 1), 'Phoenix', 'AZ', '13-week travel assignment in busy hospital setting. Housing and travel stipend provided. Immediate start available.', 'DPT degree, 1+ years acute care experience, AZ license or compact state', 1800, 2200, 'Contract', 'Mid-level', false),
('Pediatric Physical Therapist', (SELECT id FROM public.companies WHERE name = 'HealthFirst Rehabilitation' LIMIT 1), 'Portland', 'OR', 'Specialize in pediatric care in our dedicated children''s therapy center. Work with infants through adolescents with developmental delays.', 'DPT degree, pediatric experience, OR state license', 72000, 88000, 'Full-time', 'Mid-level', false),
('Director of Rehabilitation', (SELECT id FROM public.companies WHERE name = 'Advanced Sports Medicine Institute' LIMIT 1), 'Denver', 'CO', 'Leadership role overseeing PT department. Manage staff, develop protocols, and maintain clinical excellence standards.', 'DPT degree, 7+ years experience, leadership experience required', 110000, 140000, 'Full-time', 'Senior', false);