-- Add sample job listings to show companies that are hiring (for green pins on map)

-- Get company IDs first, then insert job listings
INSERT INTO job_listings (
  title,
  company_name,
  city,
  state,
  zip_code,
  description,
  requirements,
  employment_type,
  experience_level,
  salary_min,
  salary_max,
  is_remote,
  posted_by,
  source,
  latitude,
  longitude
) VALUES

-- Twin Boro Physical Therapy Jobs
(
  'Physical Therapist - Marlboro Location',
  'Twin Boro Physical Therapy',
  'Marlboro',
  'NJ',
  '07746',
  'Join our growing team at Twin Boro Physical Therapy! We are seeking a dedicated Physical Therapist to provide exceptional patient care in our Marlboro location.',
  'DPT degree required, NJ state license, 1+ years experience preferred',
  'Full-time',
  'Mid-Level',
  85000,
  95000,
  false,
  null,
  'internal',
  40.3155,
  -74.2436
),
(
  'Physical Therapist - Princeton Location',
  'Twin Boro Physical Therapy',
  'Princeton',
  'NJ',
  '08540',
  'Opportunity to work with sports medicine cases and post-surgical rehabilitation at our Princeton clinic.',
  'DPT degree, NJ license, sports medicine experience preferred',
  'Full-time',
  'Senior',
  90000,
  105000,
  false,
  null,
  'internal',
  40.3573,
  -74.6672
),

-- PT Solutions Jobs (parent company)
(
  'Regional Physical Therapist Manager',
  'PT Solutions',
  'Memphis',
  'TN',
  '38120',
  'Lead our clinical team across multiple PT Solutions locations. Great opportunity for career advancement.',
  'DPT degree, 5+ years experience, management experience preferred',
  'Full-time',
  'Senior',
  95000,
  115000,
  false,
  null,
  'internal',
  35.1174,
  -89.9711
),

-- BenchMark Physical Therapy Jobs
(
  'Staff Physical Therapist',
  'BenchMark Physical Therapy',
  'Birmingham',
  'AL',
  '35243',
  'Join BenchMark Physical Therapy and make a difference in patients'' lives. Excellent benefits and mentorship program.',
  'DPT degree required, Alabama state license',
  'Full-time',
  'Entry Level',
  75000,
  85000,
  false,
  null,
  'internal',
  33.4734,
  -86.7073
),
(
  'Physical Therapist - Sports Medicine Focus',
  'BenchMark Physical Therapy',
  'Atlanta',
  'GA',
  '30309',
  'Sports medicine focused PT position in our Atlanta location. Work with athletes and active individuals.',
  'DPT degree, Georgia license, sports medicine certification preferred',
  'Full-time',
  'Mid-Level',
  80000,
  92000,
  false,
  null,
  'internal',
  33.7879,
  -84.3875
),

-- Athletico Physical Therapy Jobs
(
  'Physical Therapist - Oak Brook HQ',
  'Athletico Physical Therapy',
  'Oak Brook',
  'IL',
  '60523',
  'Work at our headquarters location with opportunities for clinical leadership and career development.',
  'DPT degree, Illinois license, 2+ years experience',
  'Full-time',
  'Mid-Level',
  85000,
  100000,
  false,
  null,
  'internal',
  41.8369,
  -87.9392
),
(
  'Senior Physical Therapist - Milwaukee',
  'Athletico Physical Therapy',
  'Milwaukee',
  'WI',
  '53202',
  'Senior PT role in our busy Milwaukee location. Lead clinical initiatives and mentor new graduates.',
  'DPT degree, Wisconsin license, 5+ years experience, mentorship skills',
  'Full-time',
  'Senior',
  90000,
  110000,
  false,
  null,
  'internal',
  43.0349,
  -87.9073
),

-- Select Physical Therapy Jobs
(
  'Physical Therapist - Multiple Locations',
  'Select Physical Therapy',
  'Philadelphia',
  'PA',
  '19103',
  'Multiple openings across our Pennsylvania locations. Join the largest PT network in the region!',
  'DPT degree, PA license, flexible and willing to travel between locations',
  'Full-time',
  'All Levels',
  80000,
  105000,
  false,
  null,
  'internal',
  39.9500,
  -75.1667
),

-- Elite Sports & Spine Physical Therapy Jobs
(
  'Physical Therapist - Sports & Spine Specialist',
  'Elite Sports & Spine Physical Therapy',
  'Austin',
  'TX',
  '78746',
  'Join our boutique practice focused on sports injuries and spine conditions. One-on-one patient care in a premium setting.',
  'DPT degree, Texas license, manual therapy certification preferred, sports medicine experience',
  'Full-time',
  'Mid-Level',
  88000,
  98000,
  false,
  null,
  'internal',
  30.2500,
  -97.8167
)